name: Lint

on:
  push:
    branches: [test2]
  pull_request:
    branches: [test2]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.7", "3.9"]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
          pip install flake8-html
          pip install mypy

      - name: Lint with wemake-python-styleguide
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --format=html --htmldir=flake-report
          flake8 . --count --exit-zero --exclude __init__.py --max-complexity 6 --max-line-length 120 --statistics --format=html --htmldir=flake-report

      - name: Upload linter HTML report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Linter HTML report
          path: flake-report
          if-no-files-found: ignore