name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
          pip install flake8-html
          pip install mypy

      - name: Lint with wemake-python-styleguide
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --format=html --htmldir=flake-report
          flake8 . --count --exit-zero --max-complexity=6 --max-line-length=120 --statistics --format=html --htmldir=flake-report

      - name: Upload linter HTML report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Linter HTML report
          path: flake-report
          if-no-files-found: ignore

      - name: Send telegram message on fail
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.repository }} repository:
            
            ${{ github.actor }} created ${{ github.event.name }}:
            Pipeline failed!
            
            See details: https://github.com/${{ github.repository }}/actions

      - name: Send telegram message on success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.repository }} repository:
            
            ${{ github.actor }} created ${{ github.event.name }}:
            Pipeline finished successfully!
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
